name: Test master branch

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
    
    - name: Publish
      run: dotnet publish -c Release -o Build

    - name: Package
      run: |
        tar -caf iModYourAnno.zip -C ./Build/ *
    
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
    # Artifact name
        name: iMYA
        path: |
          iModYourAnno.zip
